services:
  frugaast-web:
    build:
      context: ../
      dockerfile: docker/dockerfile
      target: build-env
    container_name: frugaast-web
    restart: always
    volumes:
      - ${PWD}/..:/app
      - ${PWD}/../.env.local:/app/.env.local
      - /app/node_modules
      #- /app/.next #removed otherwise the debug breakpoints won't bind
    ports:
      - 3006:3000
      - 9231:9230
    environment:
      - DEBUG=remix:*
    working_dir: /app
    
    #entrypoint: "tail -f /dev/null"
    entrypoint: "npm run dev:debug"

    # NODE_OPTIONS="--inspect=0.0.0.0:9229" npm run dev

