services:
  frugaast-web:
    build:
      context: ../
      dockerfile: docker/dockerfile-react
      target: build-env
    container_name: frugaast-web
    restart: always
    volumes:
      - ${PWD}/..:/app
      - ${PWD}/../.env.local:/app/.env.local
      - /app/node_modules
      #- /app/.next #removed otherwise the debug breakpoints won't bind
    ports:
      - 3006:3000
    environment:
      - DEBUG=remix:*
    working_dir: /app
    
    #entrypoint: "tail -f /dev/null"
    entrypoint: "npm run dev:debug"

    # NODE_OPTIONS="--inspect=0.0.0.0:9229" npm run dev


  frugaast-api:
    build: 
      context: ../
      dockerfile: docker/dockerfile-python
    container_name: frugaast-api
    restart: unless-stopped
    volumes:
      - ${PWD}/../api:/app
      - ${PWD}/../.env.local:/app/.env.local
      - ${PWD}/../keys:/keys
    ports:
      - 4242:4242
      - 9231:9230
    env_file:
      - ../.env.local
    entrypoint: tail -f /dev/null